### ISSUE TITLE
是没有用了吗？

### ISSUE THREAD

**Issue by xkatld** [black-fruit/NineAI-Cracked#2]
部署后·一直重启
![image](https://github.com/black-fruit/NineAI-Cracked/assets/36999228/465bf9b8-c837-4809-9cf8-e3637bd58922)
![image](https://github.com/black-fruit/NineAI-Cracked/assets/36999228/bbb44a9d-eabb-4ed5-885b-52a26f9b81af)

**Comment by xkatld** [comment]
找到问题了 是globalConfig.service.js的第109行格式有问题，改一下就行了

**Comment by nljie1103** [comment]
怎么改啊，我也是这样

**Comment by xkatld** [comment]
> 

按上下格式改就行了

**Comment by xkatld** [comment]
@nljie1183 按上下文本格式改就行了
